<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests https://pmd.github.io/schema/rule-tests_1_1_0.xsd">

    <test-code>
        <description>failure case</description>
        <expected-problems>5</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (NullPointerException e) {
        } catch (Exception e) {
        } catch (RuntimeException e) {
        } catch (Throwable e) {
        } catch (Error e) {
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>catching another type, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (FooException e) {
        }
    }
}
class FooException extends RuntimeException {}
        ]]></code>
    </test-code>

    <test-code>
        <description>catching another type - violation, if so configured</description>
        <rule-property name="typesThatShouldNotBeCaught">java.lang.IllegalStateException</rule-property>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (IllegalStateException e) {
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>no longer a failure, because of configuration</description>
        <rule-property name="typesThatShouldNotBeCaught">java.lang.IllegalStateException</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (NullPointerException e) {
        } catch (Exception e) {
        } catch (RuntimeException e) {
        } catch (Throwable e) {
        } catch (Error e) {
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>validate violation message</description>
        <expected-problems>1</expected-problems>
        <expected-messages>
            <message>Avoid catching NullPointerException in try-catch block</message>
        </expected-messages>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (NullPointerException e) {
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>catching subclass of NPE, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (FooException e) {
        }
    }
}
class FooException extends NullPointerException {}
        ]]></code>
    </test-code>

    <test-code>
        <description>throwing it, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        throw new NullPointerException();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>failure case with multi-catch</description>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (NullPointerException | RuntimeException | FooException e) {
        }
    }
}
class FooException extends Exception {}
        ]]></code>
    </test-code>

    <test-code>
        <description>[java] AvoidCatchingGenericException: Can no longer suppress on the exception itself #4873</description>
        <expected-problems>0</expected-problems>
        <expected-suppressions>
            <suppressor line="5">@SuppressWarnings</suppressor>
        </expected-suppressions>
        <code><![CDATA[
public class Example {
    public void example() {
        try {
            someMethod();
        } catch(@SuppressWarnings("PMD.AvoidCatchingGenericException") Exception e) {
            e.printStackTrace();
        }
    }
}
]]></code>
    </test-code>
</test-data>
